In [ ]:
# %env CUBLAS_WORKSPACE_CONFIG=:4096:8

In [1]:
from main_multi import *
# from torchsummary import summary
import wandb

Args:
Namespace(augment=3, batch_size=128, burn_in=10, c_threshold=0.7, corruption_ratio=0.0, corruption_type=None, dataset='cifar10', device='cuda', imbalanced_factor=None, innerepochs=1, interval=1, loss_p=0.75, lr=0.1, max_epoch=100, meta_lr=0.001, meta_method='MAML', meta_net_hidden_size=80, meta_net_num_layers=0, meta_weight_decay=0.0, momentum=0.9, num_consistency=5, num_meta=1000, num_workers=0, plot_interval=10, seed=1, semi='mixlabel', semi_beta=1.0, semi_p=0.3, threshlod=-1, weight_decay=0.0005)


In [ ]:
# !wandb login b729ef7d624d9a61a7ff0f8b7dddeae0b138e8d9

In [2]:
hyperparameter = {
    'dataset':'cifar10',
    'num_meta':1000,
    'model':'resnet32',
    'milestone':[90],
    'imbalanced_factor':None,
    'corruption_type':'flip1',
    'corruption_ratio':0.4,
    'batch_size':256,
    'max_epoch':150,
    # 'device':"cuda" if torch.cuda.is_available() else "cpu",
    'device':'cuda',
    'seed': 1, # 
    'meta_net_hidden_size':80,
    'meta_net_num_layers':1,
    'lr':0.1,
    'weight_decay':5e-4,
    'momentum':0.9,
    'meta_lr':1e-3,
    'meta_weight_decay':0.,
    'meta_method':'MAML',
    'innerepochs':1,
    'inner_lr':0.1,
    'interval':1,
    'plot_interval':10,
    'burn_in':80,

    'threshold':0.2,
    'c_threshold':0.7,
    'semi':'cutmix',
    'semi_p':0.4,
    'semi_beta':1.0,
    'loss_p': 0.75,

    'num_workers':0,
    'augment':2,
    'num_consistency':5,
}

In [3]:
wandb.init(project="my-test-project", entity="ruistarlit", config=hyperparameter, mode='disabled')

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


In [22]:
Model = TrainNet(wandb.config)
# Model = TrainNet(args)
# print('DNN Model: vvvvvvvvv')
# summary(Model.model,(3,32,32))
# print('Meta-Net:  vvvvvvvvvvvv')
# summary(Model.meta_net, (1,1))

In [29]:
Model.train(30, ckp=10)

Files already downloaded and verified
[[0.6 0.  0.  0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.6 0.  0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.6 0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  0.  0.  0.  0.4 0. ]
 [0.4 0.  0.  0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.6 0.4 0.  0.  0. ]
 [0.  0.  0.  0.  0.4 0.  0.6 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.4]
 [0.  0.  0.  0.  0.  0.  0.4 0.  0.6 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.4 0.6]]
[Main] Training.... 


  0%|          | 0/30 [00:00<?, ?it/s]



[Train:11] Train loss:0.7984 acc:0.4645|Test loss:1.0956 acc:0.6434


[Train:12] Train loss:0.7654 acc:0.4674|Test loss:1.0694 acc:0.6762


[Train:13] Train loss:0.7360 acc:0.4736|Test loss:1.0846 acc:0.6562


[Train:14] Train loss:0.7603 acc:0.4726|Test loss:1.0714 acc:0.6577


[Train:15] Train loss:0.6737 acc:0.4809|Test loss:1.0827 acc:0.6903


[Train:16] Train loss:0.6402 acc:0.4821|Test loss:0.8657 acc:0.7681


[Train:17] Train loss:0.5406 acc:0.4922|Test loss:0.9587 acc:0.7323


[Train:18] Train loss:0.5110 acc:0.4938|Test loss:0.9506 acc:0.7190


[Train:19] Train loss:0.4939 acc:0.4928|Test loss:0.8676 acc:0.7470


[Train:20] Train loss:0.4879 acc:0.4950|Test loss:0.8393 acc:0.7500


[Train:21] Train loss:0.4935 acc:0.4939|Test loss:1.2375 acc:0.6360


[Train:22] Train loss:0.4614 acc:0.4927|Test loss:0.9886 acc:0.6974


[Train:23] Train loss:0.4663 acc:0.4941|Test loss:1.0238 acc:0.6987


[Train:24] Train loss:0.4442 acc:0.4956|Test loss:0.8922 acc:0.7180


[Train:25] Train l

KeyboardInterrupt: 

In [5]:
Model.load('checkpoint/CheckPoint-_04-28_03-35-best.pth.tar')

[Load] Acc:0.8979|Epoch:100|Lr:0.001


In [30]:
rweight = Model.show_weight(100)

Files already downloaded and verified
[[0.6 0.  0.  0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.6 0.  0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.6 0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  0.  0.  0.  0.4 0. ]
 [0.4 0.  0.  0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.6 0.4 0.  0.  0. ]
 [0.  0.  0.  0.  0.4 0.  0.6 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.4]
 [0.  0.  0.  0.  0.  0.  0.4 0.  0.6 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.4 0.6]]


In [31]:
rweight[:, 0:1].shape

(49000, 1)

In [32]:
np.save('rw4.npy',rweight)

In [ ]:
x, y, z = rweight[:, 0:1], rweight[:, 1:2], rweight[:, 2:3]

In [ ]:
ax = plt.figure().add_subplot(111, projection = '3d')
#基于ax变量绘制三维图
#xs表示x方向的变量
#ys表示y方向的变量
#zs表示z方向的变量，这三个方向上的变量都可以用list的形式表示
#m表示点的形式，o是圆形的点，^是三角形（marker)
#c表示颜色（color for short）
ax.scatter(x, y, z) #点为红色三角形
 
#设置坐标轴
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
 
#显示图像
plt.show()

In [ ]:
if wandb.run is not None:
    wandb.finish()