In [ ]:
# %env CUBLAS_WORKSPACE_CONFIG=:4096:8

In [ ]:
import os
# os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [1]:
from main_multi import *
# from torchsummary import summary
import wandb

Args:
Namespace(augment=3, batch_size=128, burn_in=10, c_threshold=0.7, corruption_ratio=0.0, corruption_type=None, dataset='cifar10', device='cuda', imbalanced_factor=None, innerepochs=1, interval=1, loss_p=0.75, lr=0.1, max_epoch=100, meta_lr=0.001, meta_method='MAML', meta_net_hidden_size=80, meta_net_num_layers=0, meta_weight_decay=0.0, momentum=0.9, num_consistency=5, num_meta=1000, num_workers=0, plot_interval=10, seed=1, semi='mixlabel', semi_beta=1.0, semi_p=0.3, threshlod=-1, weight_decay=0.0005)


In [ ]:
# !wandb login b729ef7d624d9a61a7ff0f8b7dddeae0b138e8d9

In [2]:
hyperparameter = {
    'dataset':'cifar10',
    'num_meta':1000,
    'model':'resnet32',
    'milestone':[90],
    'imbalanced_factor':None,
    'corruption_type':'flip1',
    'corruption_ratio':0.4,
    'batch_size':256,
    'max_epoch':150,
    # 'device':"cuda" if torch.cuda.is_available() else "cpu",
    'device':'cuda',
    'seed': 1, # 
    'meta_net_hidden_size':80,
    'meta_net_num_layers':1,
    'lr':0.1,
    'weight_decay':5e-4,
    'momentum':0.9,
    'meta_lr':1e-3,
    'meta_weight_decay':0.,
    'meta_method':'MAML',
    'innerepochs':1,
    'inner_lr':0.1,
    'interval':1,
    'plot_interval':10,
    'burn_in':80,

    'threshold':0.2,
    'c_threshold':0.7,
    'semi':'cutmix',
    'semi_p':0.4,
    'semi_beta':1.0,
    'loss_p': 0.75,

    'num_workers':0,
    'augment':2,
    'num_consistency':5,
}

In [3]:
wandb.init(project="tune-cifar10", entity="ruistarlit", config=hyperparameter)
# wandb.init(project="tune-cifar10", entity="ruistarlit", config=hyperparameter, mode="disabled")

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: ruistarlit (use `wandb login --relogin` to force relogin)


In [4]:
Model = TrainNet(wandb.config)
# Model = TrainNet(args)
# print('DNN Model: vvvvvvvvv')
# summary(Model.model,(3,32,32))
# print('Meta-Net:  vvvvvvvvvvvv')
# summary(Model.meta_net, (1,1))

In [5]:
Model.load(r'checkpoint/0.82/CheckPoint-_04-02_10-45', opt='DL')

[Load]success


In [13]:
Model.test()

[Test] Loss:0.541211| Acc:0.8639


(0.5412109091877937, 0.8639)

In [6]:
Model._set_lr(0.01)

[Main]Learning Rate is set to 0.01


In [7]:
Model.train(20, ckp=80)

Files already downloaded and verified
[[0.6 0.  0.  0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.6 0.  0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.6 0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  0.  0.  0.  0.4 0. ]
 [0.4 0.  0.  0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.6 0.4 0.  0.  0. ]
 [0.  0.  0.  0.  0.4 0.  0.6 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.4]
 [0.  0.  0.  0.  0.  0.  0.4 0.  0.6 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.4 0.6]]
[Main] Training.... 


  0%|          | 0/20 [00:00<?, ?it/s]

[Debug]  8.98%important|44.14%unimportant|46.88%normal at this batchn 5
[Debug] 12.11%important|40.62%unimportant|47.27%normal at this batchn 4
[Debug]  8.59%important|41.80%unimportant|49.61%normal at this batchn 5
[Debug]  9.38%important|46.88%unimportant|43.75%normal at this batchn 6
[Debug]  9.77%important|48.83%unimportant|41.41%normal at this batchn 6
[Debug] 11.33%important|46.48%unimportant|42.19%normal at this batchn 5
[Debug] 11.72%important|43.75%unimportant|44.53%normal at this batchn 4
[Debug] 10.94%important|46.48%unimportant|42.58%normal at this batchn 5
[Debug]  9.38%important|46.48%unimportant|44.14%normal at this batchn 5
[Debug] 10.55%important|43.36%unimportant|46.09%normal at this batchn 5
[Debug] 12.50%important|45.70%unimportant|41.80%normal at this batchn 4
[Debug] 13.67%important|43.36%unimportant|42.97%normal at this batchn 4
[Debug] 12.11%important|41.80%unimportant|46.09%normal at this batchn 4
[Debug] 17.19%important|44.14%unimportant|38.67%normal at this b

In [22]:
Model.train(10, ckp=90)

Files already downloaded and verified
[[0.6 0.  0.  0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.6 0.  0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.6 0.  0.  0.4 0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  0.  0.  0.  0.4 0. ]
 [0.4 0.  0.  0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.6 0.4 0.  0.  0. ]
 [0.  0.  0.  0.  0.4 0.  0.6 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.6 0.  0.4]
 [0.  0.  0.  0.  0.  0.  0.4 0.  0.6 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.4 0.6]]
[Main] Training.... 


  0%|          | 0/10 [00:00<?, ?it/s]

[Main]Learning Rate is set to 0.001


[Train:91] Train loss:0.0981 acc:0.5646|Test loss:0.4407 acc:0.8879


[Train:92] Train loss:0.0725 acc:0.5683|Test loss:0.4236 acc:0.8935


[Train:93] Train loss:0.0603 acc:0.5682|Test loss:0.4184 acc:0.8939


[Train:94] Train loss:0.0539 acc:0.5696|Test loss:0.4105 acc:0.8976


[Train:95] Train loss:0.0468 acc:0.5705|Test loss:0.4072 acc:0.8986


[Train:96] Train loss:0.0438 acc:0.5689|Test loss:0.4117 acc:0.8971


[Train:97] Train loss:0.0401 acc:0.5691|Test loss:0.4077 acc:0.8986


[Train:98] Train loss:0.0376 acc:0.5711|Test loss:0.4082 acc:0.9001


[Train:99] Train loss:0.0366 acc:0.5716|Test loss:0.4129 acc:0.8967


[Train:100] Train loss:0.0378 acc:0.5718|Test loss:0.4074 acc:0.9007


In [ ]:
Model.optimizer.state_dict()["param_groups"][0]["lr"]

In [ ]:
if wandb.run is not None:
    wandb.finish()